DATASET:
  TRAIN: data/ablation_filtered_data/data_Nitrides/train_data.json
  VAL: data/ablation_filtered_data/data_Nitrides/test_data.json
LOGGING:
  LOG_DIR: saved_models
  LOG_DIR_NAME: ablation_filtered_data/random_forest/Nitrides
MODEL:
  CIF_FOLDER: cif_file
  INIT_FILE: master_files/encoding/atom_init.json
  NAME: random_forest
  PRETRAINED_MODEL_PATH: _saved_models/leftnet/m1_full_lr0.01_encoding/best-mae-epoch=04-val_mae=0.43.ckpt
OUTPUT:
  DIR: predictions/random_forest
