DATASET:
  TRAIN: data/ablation_filtered_data/data_Chalcogenides/train_data.json
  VAL: data/ablation_filtered_data/data_Chalcogenides/test_data.json
LEFTNET:
  ENCODING: one-hot
  LAYER_FREEZE: none
LOGGING:
  LOG_DIR: saved_models
  LOG_DIR_NAME: ablation_filtered_data/leftnet_encoding/Chalcogenides
MODEL:
  CIF_FOLDER: cif_file
  INIT_FILE: master_files/encoding/atom_init.json
  NAME: leftnet
  PRETRAINED_MODEL_PATH: saved_models/leftnet/m1_full_lr0.01_encoding/best-mae-epoch=175-val_mae=0.43.ckpt
OUTPUT:
  DIR: result_new_data/leftnet/encoding_embedding
SOLVER:
  EPOCHS: 100
  LR: 0.001
  NUM_RUNS: 2
  TEST_RATIO: null
  TRAIN_RATIO: 0.9
  VAL_RATIO: 0.1
