DATASET:
  TRAIN: data/ablation_filtered_data/data_Halides/train_data.json
  VAL: data/ablation_filtered_data/data_Halides/test_data.json
LEFTNET:
  ENCODING: none
  LAYER_FREEZE: none
LOGGING:
  LOG_DIR: saved_models
  LOG_DIR_NAME: ablation_filtered_data/cgcnn/Halides
MODEL:
  CIF_FOLDER: cif_file
  INIT_FILE: master_files/encoding/atom_init.json
  NAME: cgcnn
  PRETRAINED_MODEL_PATH: saved_models/m1_full_lr0.01/best-mae-epoch=107-val_mae=0.39.ckpt
OUTPUT:
  DIR: result_new_data/leftnet/encoding_embedding
SOLVER:
  EPOCHS: 50
  LR: 0.001
  NUM_RUNS: 5
  TEST_RATIO: null
  TRAIN_RATIO: 0.9
  VAL_RATIO: 0.1
